language: c

env:
  global:
    secure: CXrEz/lsk1qUhRADO6P1m4rf36W6e2GnISs38R8h3xITv4QocAeeiwuJ0AaGfyCae1cmnraUovKp+A028UoMUw/hQJFK1RzHSGY1OccQyMgrDMuVwNDEF4IxNC/r3ZP69OxfDOwRmWW4a007ml519IadOPb9hY9I5X/4sO3FCu4zLy2ObPkDKfkVR08Bp4TPx9vRX38B9g/sMR7Lni6tmCGV0cjyNJrzc1WZCezWUwZ1VTUAFu0dtzvGUc13JwcjdJlLhjMKThrezEgdgqXT/LIeoCifjvpazRVRv8blcZMFK/vhuatjAmZx/sP4l3vzAoxEr13CwP8NCsG5UqpyWdNOAANm3+Bdn04g60x++n/frz8dH6UdI3RBXAMgR6OHtWyQ8FvRfJlb0ARy5kO1K9okr6HZyxMHzeAdyEwFbT156/U68ptBk4JB8JbYoptWm8UcNIAE/Unc81CpRHIdRFbhpvBjuK4zv48sUJS4PV9sz5hdKFGCavWi9c/n1MLzzEZv3nrbVjwufUa8r8Cda7dxT8B0N08NCeRz9A/neWATOivaU2wwN3B+sYWIPv0xuiqn4j2WodlglHk1NzNcZwtWnADo9minuU/Fhhn6AHF8hQ64DxBCixhC4GBZqRI4qyoIBV67NuxS4z1+nre4wh1rVF8erm84cGHdZGcPElA=

deploy:
  provider: releases
  api_key:
    secure: nt/YMiBuox5UJkY7r7i4K6RiZLQC2BmdjK7xO2sPkB4h3cl7ozASP79C2SI55LYwMnkQuJkGbuoJQ4Kf+gq9sGbblYWWg6uGiM2HdWREjNFhEdJSRZ9oKJGxSObDeU++by+V2TmpGc/fYjOz3biNVQPNhB6/Y4vGcrF3h7vgf+KiGlmJVcEMTa1QDV+AzTRbxLsGJw5u333DT7yRX7I/l9eHkrryiSPduzLiQLtWC3YawcvPRKjivo8JHWdnY5CoPM9skUmZ10j8y3KkaW3MyOlD5bEk4anuTGl+XFCjM+siDgx9xm3q5lsVO9sLW0LvIs57fvt+ktgLKVnnXLVEvu012+0Sc8HcP71XOGujSj5MR65devUNv1lKtDG6AQfwlB6wcvx1qrkcx0WclMIrQd60GSpK283wVla00SnxQWU5WatNfIP1BaLzxP6bsi+okMNMf/+c5P+wCzjE6t5JmkWNNR8Pmifj31Arnu5daUmtcKj4tf6NZzx6qwilOfr7cHOqgQoKgVC5Cas0lWi5/16VzU6+mu7thELAnFX/hcRWbmHjWX2BPa2NPLGzX083RmCXuQlQVx/4jSqoK9yRcPXaTeJ1bGvbua7XxnhEcwjmW65apwWsDs/tVfpWap6mogTFRWgLidCOuInc8+KDXQdU7nXRIoy84JAIkmSA07Q=
  file: travis_test.tar.bz2
  skip_cleanup: true
  on:
    tags: true
    repo: soburi/travis_test

before_script:
  - env
  - gem install rubyzip
  - gem install git
  - 'ZIPNAME=$(ruby dist/ci_zipname.rb)'
  - echo ZIPNAME=${ZIPNAME}

script:
  - ruby dist/ci_fetchsubmodule.rb dist/submodules.json
  - mkdir ~/${ZIPNAME}
  - cp -r * ~/${ZIPNAME}
  - echo "cd ~ && tar cfj ${PWD}/travis_test.tar.bz2 --exclude ${ZIPNAME}/.git ${ZIPNAME}/"
  - bash -c "cd ~ && tar cfj ${PWD}/travis_test.tar.bz2 --exclude ${ZIPNAME}/.git ${ZIPNAME}/"
  - git remote
  - echo git remote add gh-origin "https://github.com/${TRAVIS_REPO_SLUG}"
  - git remote add gh-origin "https://github.com/${TRAVIS_REPO_SLUG}"
  - git fetch --all
  - git branch -a
  - git checkout gh-origin/gh-pages
  - date > hoge
  - git add hoge
  - git commit -m ${TRAVIS_BUILD_ID}
    git push gh-origin gh-pages
