language: c

before_script:
  - gem install rubyzip
  - gem install git
  - 'ZIPNAME=$(ruby dist/ci_zipname.rb)'
  - echo $ZIPNAME

script:
  - ruby dist/ci_fetchsubmodule.rb dist/submodules.json
  - mkdir git log -1 --pretty=format:%ad --date=format:%Y%m%d%H%M%S

