language: c

before_script:
  - env
  - gem install rubyzip
  - gem install git
  - 'ZIPNAME=$(ruby dist/ci_zipname.rb)'
  - echo ZIPNAME=${ZIPNAME}

script:
  - ruby dist/ci_fetchsubmodule.rb dist/submodules.json
  - mkdir ~/${ZIPNAME}
  - cp -r * ~/${ZIPNAME}
  - bash -c "cd ~ && tar cvfj ${OLDPWD}/${ZIPNAME}.tar.bz2 --exclude ${ZIPNAME}/.git ${ZIPNAME}/"
