language: c

before_script:
  - gem install rubyzip
  - gem install git
  - 'ZIPNAME=$(ruby dist/ci_zipname.rb)'
  - echo ZIPNAME=${ZIPNAME}

script:
  - ruby dist/ci_fetchsubmodule.rb dist/submodules.json
  - mkdir ${ZIPNAME}

