language: c

env:
  global:
    secure: CXrEz/lsk1qUhRADO6P1m4rf36W6e2GnISs38R8h3xITv4QocAeeiwuJ0AaGfyCae1cmnraUovKp+A028UoMUw/hQJFK1RzHSGY1OccQyMgrDMuVwNDEF4IxNC/r3ZP69OxfDOwRmWW4a007ml519IadOPb9hY9I5X/4sO3FCu4zLy2ObPkDKfkVR08Bp4TPx9vRX38B9g/sMR7Lni6tmCGV0cjyNJrzc1WZCezWUwZ1VTUAFu0dtzvGUc13JwcjdJlLhjMKThrezEgdgqXT/LIeoCifjvpazRVRv8blcZMFK/vhuatjAmZx/sP4l3vzAoxEr13CwP8NCsG5UqpyWdNOAANm3+Bdn04g60x++n/frz8dH6UdI3RBXAMgR6OHtWyQ8FvRfJlb0ARy5kO1K9okr6HZyxMHzeAdyEwFbT156/U68ptBk4JB8JbYoptWm8UcNIAE/Unc81CpRHIdRFbhpvBjuK4zv48sUJS4PV9sz5hdKFGCavWi9c/n1MLzzEZv3nrbVjwufUa8r8Cda7dxT8B0N08NCeRz9A/neWATOivaU2wwN3B+sYWIPv0xuiqn4j2WodlglHk1NzNcZwtWnADo9minuU/Fhhn6AHF8hQ64DxBCixhC4GBZqRI4qyoIBV67NuxS4z1+nre4wh1rVF8erm84cGHdZGcPElA=

deploy:
  provider: releases
  api_key:
    secure: nt/YMiBuox5UJkY7r7i4K6RiZLQC2BmdjK7xO2sPkB4h3cl7ozASP79C2SI55LYwMnkQuJkGbuoJQ4Kf+gq9sGbblYWWg6uGiM2HdWREjNFhEdJSRZ9oKJGxSObDeU++by+V2TmpGc/fYjOz3biNVQPNhB6/Y4vGcrF3h7vgf+KiGlmJVcEMTa1QDV+AzTRbxLsGJw5u333DT7yRX7I/l9eHkrryiSPduzLiQLtWC3YawcvPRKjivo8JHWdnY5CoPM9skUmZ10j8y3KkaW3MyOlD5bEk4anuTGl+XFCjM+siDgx9xm3q5lsVO9sLW0LvIs57fvt+ktgLKVnnXLVEvu012+0Sc8HcP71XOGujSj5MR65devUNv1lKtDG6AQfwlB6wcvx1qrkcx0WclMIrQd60GSpK283wVla00SnxQWU5WatNfIP1BaLzxP6bsi+okMNMf/+c5P+wCzjE6t5JmkWNNR8Pmifj31Arnu5daUmtcKj4tf6NZzx6qwilOfr7cHOqgQoKgVC5Cas0lWi5/16VzU6+mu7thELAnFX/hcRWbmHjWX2BPa2NPLGzX083RmCXuQlQVx/4jSqoK9yRcPXaTeJ1bGvbua7XxnhEcwjmW65apwWsDs/tVfpWap6mogTFRWgLidCOuInc8+KDXQdU7nXRIoy84JAIkmSA07Q=
  file: ${ARCHIVENAME}.tar.bz2
  skip_cleanup: true
  on:
    tags: true
before_script:
- env
- gem install git
- source dist/setup_env.sh
- git remote add gh-origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
- git config --global user.email "travisci@example.com"
- git config --global user.name "Travis-CI"
script:

- curl -l -L https://downloads.arduino.cc/arduino-1.6.12-linux64.tar.xz | tar xvfJ - -C ~
- curl -l -L https://github.com/soburi/contiki-makehelper/releases/download/0.0.4/contiki-makehelper_x86_64-pc-linux-gnu_0.0.4.tar.bz2  | tar xvfj - -C ~
- mv ~/contiki-makehelper/* ~/arduino-1.6.12/hardware/tools/avr/
- echo intiki.contiki-makehelper=0.0.4 >> ~/arduino-1.6.12/hardware/tools/avr/builtin_tools_versions.txt 

after_script:
