language: c

deploy:
  provider: releases
  api_key:
    secure: "DDh2ogarIFcpnwsZNr6m4oXUn7JUpO1XNZD/ohkxi8LkR76zokPXxj6Bp96mLG85q+HDNpadQBzA893gTR9lgB0JlqFxvNsO98UuinAjYezhwkuewk1nwBd7OwOWLQ66T4mZdthObJGsTC5PzbHv2zCsQAPM47m4KDKZ+RLnwAp54eHnHIFZ685pVS57ozI0Ji6RMacTGJzV/zYsq6MamrOZ7gUXxkQhJ+JJdNWBHNbKlgcA1z+OtJLfAH2JlKv6dEWLu/Nq8Q0kjlfLVO2Lg1A2qO3gv0LMIMWIpn1xiZV6b0jZ+dG/17GCw5vNknyuSOCW3knORuaoj8nwCZjnOHXS2zniYWnf4B5vsYs0ngO3cPt2Yda5/DtWu4+51lkpKnq4HifyzvW8T3rMb1TNwEkmfdxRfBGQfHExVbVbgQDdzaMZdGmwxL1zR1dPjr4AVuJW4VaRXWtmi5X5y65aop/ajGGmWcZO/gWwF17Pmr68oybRnMJ3bJU0UukoSE/NQZfjMkVgvpSp+2Pn2c3GCE+BSC7mBaqpB3E8f4LeJ/2vD6Qg611Ae9vc6wjylQ2tR1Kwav7CMyce6JCb7CS/CHSslmjvKxRpGlG78+HMabKF4Ed6HaRR2Y0VQQeS2bqTerhECAY9GL/eYyZx1s27Hmwhw3hbaXkyCxntz97VKwU="
  file: travis_test.tar.bz2
  skip_cleanup: true
  on:
    tags: true

before_script:
  - env
  - gem install rubyzip
  - gem install git
  - 'ZIPNAME=$(ruby dist/ci_zipname.rb)'
  - echo ZIPNAME=${ZIPNAME}

script:
  - ruby dist/ci_fetchsubmodule.rb dist/submodules.json
  - mkdir ~/${ZIPNAME}
  - cp -r * ~/${ZIPNAME}
  - bash -c "cd ~ && tar cfj travis_test.tar.bz2 --exclude ${ZIPNAME}/.git ${ZIPNAME}/"
