language: c

deploy:
  provider: releases
  api_key:
    secure: nt/YMiBuox5UJkY7r7i4K6RiZLQC2BmdjK7xO2sPkB4h3cl7ozASP79C2SI55LYwMnkQuJkGbuoJQ4Kf+gq9sGbblYWWg6uGiM2HdWREjNFhEdJSRZ9oKJGxSObDeU++by+V2TmpGc/fYjOz3biNVQPNhB6/Y4vGcrF3h7vgf+KiGlmJVcEMTa1QDV+AzTRbxLsGJw5u333DT7yRX7I/l9eHkrryiSPduzLiQLtWC3YawcvPRKjivo8JHWdnY5CoPM9skUmZ10j8y3KkaW3MyOlD5bEk4anuTGl+XFCjM+siDgx9xm3q5lsVO9sLW0LvIs57fvt+ktgLKVnnXLVEvu012+0Sc8HcP71XOGujSj5MR65devUNv1lKtDG6AQfwlB6wcvx1qrkcx0WclMIrQd60GSpK283wVla00SnxQWU5WatNfIP1BaLzxP6bsi+okMNMf/+c5P+wCzjE6t5JmkWNNR8Pmifj31Arnu5daUmtcKj4tf6NZzx6qwilOfr7cHOqgQoKgVC5Cas0lWi5/16VzU6+mu7thELAnFX/hcRWbmHjWX2BPa2NPLGzX083RmCXuQlQVx/4jSqoK9yRcPXaTeJ1bGvbua7XxnhEcwjmW65apwWsDs/tVfpWap6mogTFRWgLidCOuInc8+KDXQdU7nXRIoy84JAIkmSA07Q=
  file: travis_test.tar.bz2
  skip_cleanup: true
  on:
    tags: true
    repo: soburi/travis_test

before_script:
  - env
  - gem install rubyzip
  - gem install git
  - 'ZIPNAME=$(ruby dist/ci_zipname.rb)'
  - echo ZIPNAME=${ZIPNAME}

script:
  - ruby dist/ci_fetchsubmodule.rb dist/submodules.json
  - mkdir ~/${ZIPNAME}
  - cp -r * ~/${ZIPNAME}
  - bash -c "cd ~ && tar cfj ${OLDPWD}/travis_test.tar.bz2 --exclude ${ZIPNAME}/.git ${ZIPNAME}/"
